#languageCode = "en-us"
DefaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
title = "Gregory Bonaert"
baseurl = "/"
theme = "prologue-theme"

[params]
  name = "Gregory Bonaert"
  copyright = "Gregory Bonaert"
  email = "gregory@bonaert.eu"
  github = "https://github.com/harokb"


[[params.social]]
  medium = "github"
  icon = "github"
  link = "https://github.com/harokb"


[[params.social]]
  medium = "email"
  icon = "envelope"
  link = "mailto:gregory@bonaert.eu"

# Portfolio column one

[[params.portfolio1]]
  title = "LusoLeaves - Business"
  alt = "Lusoleaves - a business website."
  source = "/img/lusoleaves.png"
  url = "portfolio/lusoleaves"


# Portfolio column two

[[params.portfolio2]]
  title = "Projet Bordet - Medical"
  alt = "Projet Bordet - a medical website"
  source = "/img/difdiag.png"
  url = "portfolio/bordet"


# Portfolio column 3

#[[params.portfolio3]]
#  title = "Magna Nullam"
#  alt = ""
#  source = "/img/pic04.jpg"
#  url = "#"

[Languages]
[Languages.en]
urlFragment = ""
[Languages.fr]
urlFragment = "fr/"
